server:
  port: 8086
  servlet:
    context-path: /api

logging:
  level:
    root: ${LOG_LEVEL:INFO}

okta:
  oauth2:
    issuer: ${OKTA_ISSUER:https://dev-18092578.okta.com/oauth2/default}
    audience: ${OKTA_AUDIENCE:api://default}